base/urls.py
from django.urls import include, path
from .views import TodoList, DetailTask, CreateTask, EditTask, DeleteTask, CustomLogin, CustomLogout

urlpatterns = [
    path('todo', TodoList.as_view(), name='todo'), 
    path('task/<int:pk>', DetailTask.as_view(), name='detail'),
    path('create-task/', CreateTask.as_view(), name='create-task'),
    path('edit-task/<int:pk>', EditTask.as_view(), name='edit-task'),
    path('delete-task/<int:pk>', DeleteTask.as_view(), name='delete-task'),
    path("todo/login/", CustomLogin.as_view(), name='login'),
    path("todo/logout/", CustomLogout.as_view(), name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True, blank=True)
    title = models.CharField(max_length=200, default = '')
    description = models.TextField(null = True, blank = True)
    completed = models.BooleanField(default = False)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['completed']

base/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from .models import Task

# Create your views here.

class CustomLogin(LoginView):
    def get_success_url(self) -> str:
        return reverse_lazy('todo')
    
class CustomLogout(LogoutView):
    def get_success_url(self) -> str:
        return reverse_lazy('login')

class TodoList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'base/todo_list.html'
    login_url = 'login'

class DetailTask(LoginRequiredMixin, PermissionRequiredMixin,  DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'
    permission_required = ['base.view_task']

class CreateTask(LoginRequiredMixin, PermissionRequiredMixin,  CreateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('todo')
    template_name = 'base/task_update.html'
    permission_required = ['base.view_task']

class EditTask(LoginRequiredMixin,PermissionRequiredMixin,  UpdateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('todo')
    template_name = 'base/task_update.html'
    permission_required = ['base.view_task']

class DeleteTask(LoginRequiredMixin, PermissionRequiredMixin,  DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todo')
    template_name = 'base/task_delete_confirmation.html'
    permission_required = ['base.view_task']

base/templates/base/task.html
<h1> Title: {{task.title}} </h1>
<h3> created: {{task.created}} </h3>

<a href='/todo' > Volver </a>

base/templates/base/task_delete_confirmation.html
<a href='/todo' > Volver </a>

<form method='POST'>
    
    {% csrf_token %}
    <p>Are you sure to delete, task {{ task.id }} ?</p>
    <input type='submit' value='Delete' >

</form>

base/templates/base/task_update.html
<h1> New task form </h1>
<a href='/todo' > Volver </a>
<form method="POST" action="" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value="Send" >
</form> 

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

base/templates/base/todo_list.html
{% if user.is_authenticated %}

<p>{{ user }}</p>

<form method="post" action="{% url 'logout' %}">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>

{% else %}

<p>User is not logged in</p>
<a href="todo/login"> Login </a>

{% endif %}

<h1>
  These are my task to do
  <h1>
    <h4>
      <a href="/create-task"> Create new task </a>
    </h4>

    <table>
      <tr>
        <th>id</th>
        <th>Elements</th>
        <th>View</th>
        {% if perms.base.delete_task and perms.base.change_task  %}
        <th>Edit</th>
        <th>Delete</th>
        {% endif %}
      </tr>

      <tr>
        {% for task in tasks %}
      </tr>

      <tr>
        <td>{{ task.id }}</td>
        <td>{{ task.title }}</td>
        <td>
          <a href="/task/{{ task.id }}"> View </a>
        </td>

        {% if perms.base.delete_task and perms.base.change_task  %}
        <td>
          <a href="/edit-task/{{ task.id }}"> Edit </a>
        </td>
        <td>
          <a href="/delete-task/{{ task.id }}"> Delete </a>
        </td>
        {% endif %}
      </tr>
      {% empty %}
      <h3>Theres is no elements on the list</h3>
      {% endfor %}
    </table>
  </h1>
</h1>